use_frameworks!

target 'podTestViewController_Example' do
  pod 'podTestViewController', :path => '../'

  target 'podTestViewController_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
